site_name: earth.txt
site_url: https://www.earthtxt.org/
site_description: A .txt file for Earth.
site_author: Scape Foundation
lang: en

repo_name: 'GitHub'
repo_url: https://github.com/scape-foundation/earth-txt/
edit_uri_template: 'docs/{path}'

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: scapefoundation
    # primary: light blue
  logo: assets/image/earthtxt_logo_light.png
  favicon: assets/favicon/favicon.ico
  # features:
  #   - navigation.tabs

extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

extra:
  generator: false
  analytics:
    provider: google
    property: G-SKTRV2L8KR
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.scape.foundation
    - icon: fontawesome/brands/github 
      link: https://github.com/scape-foundation/
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/scape-foundation/
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/scape.foundation/
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/scape.foundation/

copyright: Copyright &copy; 2023 Stichting Scape Foundation

hide:
  - footer

nav:
  - Introduction: 'index.md'
  - Quick Start: 'quick_start.md'
  - Guide:
      - 'Template': 'guide/template.md'
      - 'Fields': 'guide/fields.md'
  - Resources:
      - 'FAQ': 'resources/faq.md'
      - 'Glossary': 'resources/glossary.md'
      - 'TXT Files': 'resources/txt_files.md'
      - 'References': 'resources/references.md'
      - 'Links': 'resources/links.md'
  - About:
      - 'Background': 'about/background.md'
      - 'Authors': 'about/authors.md'
      - 'Contact': 'about/contact.md'
  - Development:
      - 'Roadmap': 'development/roadmap.md'
      - 'Contributing': 'development/contributing.md'
      - 'Code of Conduct': 'development/code_of_conduct.md'
  - Legal Information:
      - 'License': 'legal/license.md'
      - 'Privacy Policy': 'legal/privacy_policy.md'
      - 'Disclaimer': 'legal/disclaimer.md'